### PR TITLE
add javac support

### PR DESCRIPTION
**Pull request by mdouek**
I understand there's a lot more commands to be supported, but at least if possible add Javac and other most used commands.

### CODE REVIEW

**Comment by FelixSelter** [comment]
Hi, thank you. I will publish an update that introduces the "link" command. With it you can create these shortcuts as simple as "jenv link javac"
It will probably come in a few hours when I have a break or tomorrow when weekend arrives.

For this reason I will not merge this PR. I hope you understand this. Thank you again for your support

**Comment by mdouek** [comment]
Yes totally understand, or was more as raising the issue and suggesting a possible fix. Thank you

**Comment by FelixSelter** [comment]
Current issue is #26 if you want to follow it

**Comment by FelixSelter** [comment]
Jenv link was implemented. Refer to readme for usability

**Pull request closed without merging**
